// ==============================================
// Arsist Engine - Logic to C# Code Generator
// UnityProject/Assets/Arsist/Editor/LogicCodeGenerator.cs
// ==============================================

using UnityEngine;
using UnityEditor;
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Arsist.Builder
{
    /// <summary>
    /// ビジュアルロジックグラフからC#コードを生成
    /// </summary>
    public static class LogicCodeGenerator
    {
        /// <summary>
        /// ロジックグラフJSONからC#スクリプトを生成
        /// </summary>
        public static void GenerateFromJSON()
        {
            var logicPath = Path.Combine(Application.dataPath, "ArsistGenerated", "logic_graphs.json");
            if (!File.Exists(logicPath))
            {
                Debug.Log("[Arsist] No logic graphs to process");
                return;
            }

            var logicJson = File.ReadAllText(logicPath);
            var graphs = JArray.Parse(logicJson);

            foreach (JObject graph in graphs)
            {
                GenerateScript(graph);
            }

            AssetDatabase.Refresh();
        }

        private static void GenerateScript(JObject graph)
        {
            var graphName = graph["name"]?.ToString() ?? "GeneratedLogic";
            var className = SanitizeClassName(graphName);
            
            Debug.Log($"[Arsist] Generating script: {className}");

            var sb = new StringBuilder();
            
            // ヘッダー
            sb.AppendLine("// Auto-generated by Arsist Engine");
            sb.AppendLine("// Do not modify manually");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine("using UnityEngine.XR.Interaction.Toolkit;");
            sb.AppendLine("using DG.Tweening;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections;");
            sb.AppendLine();
            sb.AppendLine("namespace Arsist.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {className} : MonoBehaviour");
            sb.AppendLine("    {");
            
            // 変数宣言
            GenerateVariables(sb, graph);
            
            // イベントメソッド
            GenerateEventMethods(sb, graph);
            
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // ファイル保存
            var outputPath = Path.Combine(Application.dataPath, "Arsist", "Generated", $"{className}.cs");
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
            File.WriteAllText(outputPath, sb.ToString());
            
            Debug.Log($"[Arsist] Script saved: {outputPath}");
        }

        private static void GenerateVariables(StringBuilder sb, JObject graph)
        {
            var nodes = graph["nodes"] as JArray;
            if (nodes == null) return;

            sb.AppendLine("        // === Variables ===");
            
            var declaredVars = new HashSet<string>();
            
            foreach (JObject node in nodes)
            {
                if (node["type"]?.ToString() == "variable")
                {
                    var varName = node["data"]?["variableName"]?.ToString();
                    var varType = node["data"]?["variableType"]?.ToString() ?? "float";
                    var defaultValue = node["data"]?["defaultValue"];
                    
                    if (!string.IsNullOrEmpty(varName) && !declaredVars.Contains(varName))
                    {
                        declaredVars.Add(varName);
                        var csType = MapToCSharpType(varType);
                        var csDefault = GetDefaultValue(varType, defaultValue);
                        sb.AppendLine($"        public {csType} {varName} = {csDefault};");
                    }
                }
            }
            
            sb.AppendLine();
        }

        private static void GenerateEventMethods(StringBuilder sb, JObject graph)
        {
            var nodes = graph["nodes"] as JArray;
            var connections = graph["connections"] as JArray;
            
            if (nodes == null) return;

            // イベントノードを収集
            var eventNodes = new List<JObject>();
            var nodeMap = new Dictionary<string, JObject>();
            
            foreach (JObject node in nodes)
            {
                var nodeId = node["id"]?.ToString();
                if (!string.IsNullOrEmpty(nodeId))
                {
                    nodeMap[nodeId] = node;
                }
                
                if (node["type"]?.ToString() == "event")
                {
                    eventNodes.Add(node);
                }
            }

            // 接続マップを作成
            var connectionMap = new Dictionary<string, List<string>>();
            if (connections != null)
            {
                foreach (JObject conn in connections)
                {
                    var from = conn["from"]?.ToString();
                    var to = conn["to"]?.ToString();
                    if (!string.IsNullOrEmpty(from) && !string.IsNullOrEmpty(to))
                    {
                        if (!connectionMap.ContainsKey(from))
                            connectionMap[from] = new List<string>();
                        connectionMap[from].Add(to);
                    }
                }
            }

            // 各イベントのメソッドを生成
            foreach (var eventNode in eventNodes)
            {
                var eventType = eventNode["data"]?["eventType"]?.ToString() ?? "OnStart";
                var nodeId = eventNode["id"]?.ToString();
                
                sb.AppendLine($"        // === {eventType} ===");
                
                switch (eventType)
                {
                    case "OnStart":
                        sb.AppendLine("        private void Start()");
                        break;
                    case "OnUpdate":
                        sb.AppendLine("        private void Update()");
                        break;
                    case "OnGazeEnter":
                        sb.AppendLine("        public void OnGazeEnter()");
                        break;
                    case "OnGazeExit":
                        sb.AppendLine("        public void OnGazeExit()");
                        break;
                    case "OnSelect":
                        sb.AppendLine("        public void OnSelect(SelectEnterEventArgs args)");
                        break;
                    default:
                        sb.AppendLine($"        public void On{eventType}()");
                        break;
                }
                
                sb.AppendLine("        {");
                
                // 接続されたアクションを処理
                if (!string.IsNullOrEmpty(nodeId) && connectionMap.ContainsKey(nodeId))
                {
                    foreach (var targetId in connectionMap[nodeId])
                    {
                        if (nodeMap.ContainsKey(targetId))
                        {
                            GenerateAction(sb, nodeMap[targetId], nodeMap, connectionMap, 3);
                        }
                    }
                }
                
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        private static void GenerateAction(StringBuilder sb, JObject node, 
            Dictionary<string, JObject> nodeMap, 
            Dictionary<string, List<string>> connectionMap,
            int indentLevel)
        {
            var indent = new string(' ', indentLevel * 4);
            var nodeType = node["type"]?.ToString();
            var nodeId = node["id"]?.ToString();

            if (nodeType != "action") return;

            var actionType = node["data"]?["actionType"]?.ToString() ?? "";
            var target = node["data"]?["target"]?.ToString() ?? "gameObject";

            switch (actionType)
            {
                case "SetActive":
                    var active = node["data"]?["parameters"]?["active"]?.Value<bool>() ?? true;
                    sb.AppendLine($"{indent}{target}.SetActive({active.ToString().ToLower()});");
                    break;

                case "PlayAnimation":
                    var animName = node["data"]?["parameters"]?["animationName"]?.ToString() ?? "Idle";
                    sb.AppendLine($"{indent}{target}.GetComponent<Animator>().Play(\"{animName}\");");
                    break;

                case "MoveTo":
                    var posX = node["data"]?["parameters"]?["x"]?.Value<float>() ?? 0;
                    var posY = node["data"]?["parameters"]?["y"]?.Value<float>() ?? 0;
                    var posZ = node["data"]?["parameters"]?["z"]?.Value<float>() ?? 0;
                    var duration = node["data"]?["parameters"]?["duration"]?.Value<float>() ?? 1;
                    sb.AppendLine($"{indent}{target}.transform.DOMove(new Vector3({posX}f, {posY}f, {posZ}f), {duration}f);");
                    break;

                case "RotateTo":
                    var rotX = node["data"]?["parameters"]?["x"]?.Value<float>() ?? 0;
                    var rotY = node["data"]?["parameters"]?["y"]?.Value<float>() ?? 0;
                    var rotZ = node["data"]?["parameters"]?["z"]?.Value<float>() ?? 0;
                    var rotDuration = node["data"]?["parameters"]?["duration"]?.Value<float>() ?? 1;
                    sb.AppendLine($"{indent}{target}.transform.DORotate(new Vector3({rotX}f, {rotY}f, {rotZ}f), {rotDuration}f);");
                    break;

                case "ScaleTo":
                    var scaleX = node["data"]?["parameters"]?["x"]?.Value<float>() ?? 1;
                    var scaleY = node["data"]?["parameters"]?["y"]?.Value<float>() ?? 1;
                    var scaleZ = node["data"]?["parameters"]?["z"]?.Value<float>() ?? 1;
                    var scaleDuration = node["data"]?["parameters"]?["duration"]?.Value<float>() ?? 1;
                    sb.AppendLine($"{indent}{target}.transform.DOScale(new Vector3({scaleX}f, {scaleY}f, {scaleZ}f), {scaleDuration}f);");
                    break;

                case "FadeIn":
                    var fadeInDuration = node["data"]?["parameters"]?["duration"]?.Value<float>() ?? 0.5f;
                    sb.AppendLine($"{indent}{target}.GetComponent<CanvasGroup>()?.DOFade(1f, {fadeInDuration}f);");
                    break;

                case "FadeOut":
                    var fadeOutDuration = node["data"]?["parameters"]?["duration"]?.Value<float>() ?? 0.5f;
                    sb.AppendLine($"{indent}{target}.GetComponent<CanvasGroup>()?.DOFade(0f, {fadeOutDuration}f);");
                    break;

                case "PlaySound":
                    var soundName = node["data"]?["parameters"]?["soundName"]?.ToString() ?? "click";
                    sb.AppendLine($"{indent}AudioSource.PlayClipAtPoint(Resources.Load<AudioClip>(\"Sounds/{soundName}\"), {target}.transform.position);");
                    break;

                case "SetVariable":
                    var varName = node["data"]?["parameters"]?["variableName"]?.ToString();
                    var varValue = node["data"]?["parameters"]?["value"]?.ToString() ?? "0";
                    sb.AppendLine($"{indent}{varName} = {varValue};");
                    break;

                case "Log":
                    var message = node["data"]?["parameters"]?["message"]?.ToString() ?? "Debug";
                    sb.AppendLine($"{indent}Debug.Log(\"{message}\");");
                    break;

                case "Wait":
                    var waitDuration = node["data"]?["parameters"]?["duration"]?.Value<float>() ?? 1;
                    sb.AppendLine($"{indent}yield return new WaitForSeconds({waitDuration}f);");
                    break;

                case "Condition":
                    var condition = node["data"]?["parameters"]?["condition"]?.ToString() ?? "true";
                    sb.AppendLine($"{indent}if ({condition})");
                    sb.AppendLine($"{indent}{{");
                    // true分岐の接続を処理
                    if (!string.IsNullOrEmpty(nodeId) && connectionMap.ContainsKey(nodeId + "_true"))
                    {
                        foreach (var targetId in connectionMap[nodeId + "_true"])
                        {
                            if (nodeMap.ContainsKey(targetId))
                            {
                                GenerateAction(sb, nodeMap[targetId], nodeMap, connectionMap, indentLevel + 1);
                            }
                        }
                    }
                    sb.AppendLine($"{indent}}}");
                    break;

                default:
                    sb.AppendLine($"{indent}// Unknown action: {actionType}");
                    break;
            }

            // 次のアクションを連鎖処理
            if (!string.IsNullOrEmpty(nodeId) && connectionMap.ContainsKey(nodeId))
            {
                foreach (var targetId in connectionMap[nodeId])
                {
                    if (nodeMap.ContainsKey(targetId))
                    {
                        GenerateAction(sb, nodeMap[targetId], nodeMap, connectionMap, indentLevel);
                    }
                }
            }
        }

        private static string SanitizeClassName(string name)
        {
            var result = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    result.Append(c);
                }
            }
            if (result.Length > 0 && char.IsDigit(result[0]))
            {
                result.Insert(0, '_');
            }
            return result.Length > 0 ? result.ToString() : "GeneratedScript";
        }

        private static string MapToCSharpType(string arsistType)
        {
            return arsistType switch
            {
                "number" or "float" => "float",
                "int" or "integer" => "int",
                "string" or "text" => "string",
                "bool" or "boolean" => "bool",
                "vector3" => "Vector3",
                "color" => "Color",
                "gameobject" => "GameObject",
                _ => "object"
            };
        }

        private static string GetDefaultValue(string type, JToken value)
        {
            if (value == null)
            {
                return type switch
                {
                    "number" or "float" => "0f",
                    "int" or "integer" => "0",
                    "string" or "text" => "\"\"",
                    "bool" or "boolean" => "false",
                    "vector3" => "Vector3.zero",
                    "color" => "Color.white",
                    "gameobject" => "null",
                    _ => "null"
                };
            }

            return type switch
            {
                "number" or "float" => $"{value.Value<float>()}f",
                "int" or "integer" => value.Value<int>().ToString(),
                "string" or "text" => $"\"{value.ToString()}\"",
                "bool" or "boolean" => value.Value<bool>().ToString().ToLower(),
                _ => "null"
            };
        }
    }
}
